version: '3.7'

services:

  # The web service uses an image that’s built from the Dockerfile
  # in the ./app directory.
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./app/:/usr/src/app/
#    ports:
#      - 8000:8000
    # port 8000 is only exposed internally, to other Docker services.
    # The port will not be published to the host machine.
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    depends_on:
      - postgres-db

  postgres-db:
    image: library/postgres:12.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env.prod.db

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
